cons_format = "{icon}"

[theme]
theme = "slick"

[icons]
icons = "awesome5"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "focused_window"

[[block]]
block = "cpu"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

[[block]]
block = "net"
device = "wlp4s0"
format = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
interval = 5
#use_bits = false

[[block]]
block = "external_ip"
format = " $ip - $city@$region"

[[block]]
block = "nvidia_gpu"
format = " $icon 960M $utilization "
interval = 5

[[block]]
block = "time"
interval = 60
[block.format]
full = " $timestamp.datetime(f:'%a %d/%m %R') "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "backlight"
device = "intel_backlight"
