cons_format = "{icon}"

[theme]
theme = "slick"

[icons]
icons = "awesome5"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "focused_window"

[[block]]
block = "cpu"

#[[block]]
#block = "memory"
#format = "$icon $mem_total_used_percents.eng(w:2) "
#format_alt = "$icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 15
warning = 20.0
alert = 10.0
format = "$icon root: $available.eng(w:2) "

[[block]]
block = "net"
device = "wlp3s0"
format = "$icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
interval = 15
#use_bits = false

#[[block]]
#block = "external_ip"
#format = "$ip@$region_code"

[[block]]
block = "time"
interval = 60
[block.format]
full = "$icon $timestamp.datetime(f:'%a %m/%d %R') "
short = "$icon $timestamp.datetime(f:%R) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "alsamixer"

#[[block]]
#block = "backlight"
#device = "intel_backlight"

# Controls all monitor's brightness!
[[block]]
block = "xrandr"
format = "$icon$display - $brightness_icon$brightness"

[[block]]
block = "pacman"
signal = 1
