#theme = "solarized-dark"
theme = "slick"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"
clickable = true

[[block]]
block = "cpu"
#format = "CPU: {utilization}%"
interval = 5

#[[block]]
#block = "load"
#interval = 5
#format = "{1m}"

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

[[block]]
block = "net"
device = "wlp4s0"
#format = "{ssid} {signal_strength} {ip} {speed_down} {speed_up}"
format = "{ssid} {signal_strength} {speed_down} {speed_up}"
interval = 5
#use_bits = false

[[block]]
block = "nvidia_gpu"
label = "960M"
show_memory = true
show_clocks = false
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "backlight"
device = "intel_backlight"

