# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/

# monitor=,addreserved, 0, 0, 0, 0 # Custom reserved area

# HDMI port: mirror display. To see device name, use `hyprctl monitors`

dwindle {
    pseudotile = true
}

input {
    touchpad {
        natural_scroll = yes
        scroll_factor = 0.7
    }
}

binds {
    allow_workspace_cycles = true
}