# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# Open App in specific workspace rules

windowrule = workspace 1, match:class ^(kitty)$
windowrule = workspace 1, match:class ^(Alacritty)$
windowrule = workspace 2, match:class ^(firefox)$
windowrule = workspace 2, match:class ^(brave-browser)$
windowrule = workspace 2, match:class ^(microsoft-edge)$
windowrule = workspace 3, match:class (.*Nautilus)$
windowrule = workspace 3, match:class ^Slack$
windowrule = workspace 3, match:class ^(org.kde.dolphin)$
windowrule = workspace 4, match:class ^([Cc]ode.*)$

